services:
  api:
    container_name: api
    build: .
    volumes:
      - ./src:/home/node/app/src/
      - ./nodemon.json:/home/node/app/nodemon.json
    ports:
      - 8081:8081
    depends_on:
      - mailhog

  mailhog:
    container_name: mailhog
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
