@base_url = http://localhost:8081

# @base_url = https://email-notification-api-2z3o.onrender.com

###

POST {{base_url}}/
Content-Type: application/json

{
  "from": "matheussilvamartins1714@gmail.com",
  "to": "matheussilvamartins1714@gmail.com",
  "subject": "Matheus Mota",
  "text": "teste"
}